name: Upload secrets and deploy to Vercel

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    AVALANCHE_FUJI_RPC_URL: ${{ secrets.AVALANCHE_FUJI_RPC_URL }}
    X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}

on:
    push:

jobs:
    change-environment-variable:
        name: Upload secrets and deploy to Vercel
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Upload secrets and get version number
              id: get-version
              run: |
                  SECRET_VERSION=$(bash ../.github/workflows/deploy.sh | bash ../.github/workflows/get-version-number.sh)
                  echo "SECRET_VERSION=$SECRET_VERSION" >> "$GITHUB_OUTPUT"
              working-directory: ./app
            - name: Remove old environment variables and upload new ones
              run: |
                  vercel env rm SECRET_VERSION preview --yes --token=${{ secrets.VERCEL_API_TOKEN }}
                  echo "${{ steps.get-version.outputs.SECRET_VERSION }}" | vercel env add SECRET_VERSION preview --token=${{ secrets.VERCEL_API_TOKEN }}
              working-directory: ./app
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
              working-directory: ./app
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_API_TOKEN }}
              working-directory: ./app
            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_API_TOKEN }} --cwd ./
              working-directory: ./app
##            - name: Deploy Project Artifacts to Vercel
##              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_API_TOKEN }}
##              working-directory: ./app
##            - name: Deploy Project Artifacts to Vercel
##              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_API_TOKEN }}
##              working-directory: ./app
